[package]
name = "lo3"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lo3"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
chrono = "0.4.38"